### ISSUE TITLE
Could not see the wifi printer

### ISSUE THREAD

**Issue by bpcuong2013** [auctifera-josed/starprnt#17]
We setup a wifi printer. The android device sees it, and can send document to it. But the demo app can not see the printer. How to solve it? Thanks!

**Comment by infoxicator** [comment]
@bpcuong2013 What is the printer model? also try testing this on the Official Star Demo application for android that comes with the SDK  and make sure it works there so we know if it is a connection problem or the plugin. Also check that you are using the correct emulation for your printer model

**Comment by bpcuong2013** [comment]
Our printer model is EPSON - Thermal printer.

We also tried the app below, and it has the same issue.
https://play.google.com/store/apps/details?id=com.StarMicronics.StarIOSDK&hl=en

**Comment by infoxicator** [comment]
Hi @bpcuong2013 this plugin is only compatible with STAR Micronics printers. You need to search for a plugin for EPSON printers
