### ISSUE TITLE
Error: Unsupported system library

### ISSUE THREAD

**Issue by sourcer18** [auctifera-josed/starprnt#2]
I get the following error when installing the repository in the project:
![image](https://cloud.githubusercontent.com/assets/6040292/21521020/5705a11c-ccf9-11e6-9b48-9741f981414a.png)
What should I do to fix it and be able to use the repository?

**Comment by auctifera-josed** [comment]
Hi @sourcer18, I haven't develop anything for Android yet, maybe you are getting the error because you have that platform installed when installing the plugin. If you are developing for Android, we have plans of adding support to Android in the coming months, but not sure when.
