### ISSUE TITLE
Unable to found any available printer.

### ISSUE THREAD

**Issue by jasonchong3329** [auctifera-josed/starprnt#23]
Hi guy,
I'm using below code to find available printer , but it return empty array.
Does anyone facing this issue before?
i would like to connect my Epson TM-82 Lan printer.

  this.starprnt.portDiscovery('all')
      .then((res: any) => console.log(res))
      .catch((error: any) => console.error(error));

**Comment by infoxicator** [comment]
Hi @jasonchong3329 unfortunately this library is only compatible with Star Micronics printers
