### ISSUE TITLE
PrintObj not valid if cutReceipt property not present?

### ISSUE THREAD

**Issue by daniellizik** [auctifera-josed/starprnt#27]
Testing on:

- os x 10.13.6
- cordova 8.0.0
- cordova-ios 4.5.5
- ipad6
- star micronics sm-s210i

the following prints successfully:
```js
starprnt.printRawText('BT:PRNT Star', 'StarPRNT', { cutReceipt: false, text: 'foobar' });
```

the following silently fails, it actually triggers the success callback but the device never prints
```js
starprnt.printRawText('BT:PRNT Star', 'StarPRNT', { text: 'foobar' }, (wasSuccess) => alert(wasSuccess));
```

**Comment by infoxicator** [comment]
Hi @daniellizik I think that parameter is required on the printRawText function. You should use the print() function instead thats gives more flexibility and options. thanks

**Comment by daniellizik** [comment]
@infoxicator  yep `print` with `appendRawBytes` let's me send escpos as a byte array, as per the docs, thank you!
