### ISSUE TITLE
Print not working on bluetooth printer

### ISSUE THREAD

**Issue by esthonwood** [auctifera-josed/starprnt#3]
The open cash drawer works but it doesn't print on TSP100 bluetooth printer. It doesn't even throw any errors. I haven't tried other printers as that's the only one I have. Any suggestions? Thanks.

**Comment by auctifera-josed** [comment]
I have only tested on the TSP700II, give me the weekend to tested on the TSP100

**Comment by esthonwood** [comment]
@auctifera-josed I'm willing to wait :) I need this to work for my client. Thank you so much for your plugin!

**Comment by esthonwood** [comment]
Hi @auctifera-josed! Just a follow up. The error I get on all print functions is this: "Please re connect to the printer, something is not working as expected." It's on line 606 of StarPRNT.m.

The `portDiscovery()` and `connect()` functions work fine but when I call any of the print functions, I get the error above.

**Comment by auctifera-josed** [comment]
Hi @esthonwood I thought I had a TSP100 in the storage room, turns out they sent us another TSP700II by mistake, it'll take a while to change it so I can test. 

But I went over the [SDK Documentation](http://www.starmicronics.com/support/ZipFile.aspx?sat2=203&id=203&type=4&referrer=http://www.starmicronics.com/support/SDKDocumentation.aspx&tabText) and it looks like the TSP100 uses a different emulation (StarGraphic) than TSP700II (StarLine) and I only use the StarIoExtEmulationStarLine all over the code so that's why you are getting this alert from line 606 because in line 604 the _printerManager.port will always be null.

I believe just changing the emulation (or have it dynamically assigned depending on the printer) will make this plugin work with the TSP100 emulation.

**Comment by esthonwood** [comment]
Hi @auctifera-josed How can I change the emulation?

**Comment by esthonwood** [comment]
Hi! I was wondering if you have already tested this plugin in TSP100 printer? Thank you! 😊 


Best regards,

Esthon Wood

**Comment by auctifera-josed** [comment]
Hi @esthonwood, sorry man I've been really busy and haven't been able to work on this, I believe all you need to do is change the `StarIoExtEmulationStarLine` for `StarIoExtEmulationStarGraphic` which is the TSP100 emulation.

**Comment by esthonwood** [comment]
Hi! I changed the emulation to StarIoExtEmulationStarGraphic but it didn’t print anything. Can you at least tell me if my code is correct? Because I keep getting errors like "Please connect to the printer before sending commands." and "Please re connect to the printer, something is not working as expected." 

I desperately need this to work on TSP100 printer. I really appreciate you taking the time to help me. Here’s a snippet of my code:


declare let starprnt: any;

export class TestPage {
	starPort: any;
	
	openCashDrawer() { 
		starprnt.connect("BT:TSP100", function(err,res) { 
			if (err) { 
				console.log('FAILED: ' + JSON.stringify(err)); 
			} else if(res) { 
				console.log('OK: ' + JSON.stringify(res)); 
				var openOK = function(res){ 
					console.log('OK: Did it actually open? Data: ' + JSON.stringify(res));
				} 

				var openErr = function(res){ 
					console.log('FAILED: ' + JSON.stringify(res));
				}; 				
				starprnt.openCashDrawer(openOK, openErr); 
			} 
		});
	} 

	printReceipt() { 
		starprnt.connect("BT:TSP100", function(err,res) { 
			if (err) { 
				console.log('FAILED: ' + JSON.stringify(err)); 
			} else if(res) { 
				console.log('OK: ' + JSON.stringify(res)); 
				var printOK = function(res){ 
					console.log('OK: Did it actually open? Data: ' + JSON.stringify(res));
				} 

				var printErr = function(res){ 
					console.log('FAILED: ' + JSON.stringify(res));
				}; 				
				
				let content = "Star Clothing Boutique\n123 Star Road\nCity, State 12345\n";

				starprnt.printData(content, printOK, printErr);
			} 
		});
	} 
}

Best regards,

Esthon Wood
esthonwood.trulyrichclub.com

**Comment by esthonwood** [comment]
Hi @auctifera-josed! I changed the emulation to **StarIoExtEmulationStarGraphic** but it didn’t print anything. Can you at least tell me if my code is correct? Because I keep getting errors like

**"Please connect to the printer before sending commands."** and
**"Please re connect to the printer, something is not working as expected."**

I desperately need this to work on TSP100 printer. I really appreciate you taking the time to help me. Here’s a snippet of my code:


```
declare let starprnt: any;

export class TestPage {
	starPort: any;

	openCashDrawer() {
		starprnt.connect("BT:TSP100", function(err,res) {
			if (err) {
				console.log('FAILED: ' + JSON.stringify(err));
			} else if(res) {
				console.log('OK: ' + JSON.stringify(res));
				var openOK = function(res){
					console.log('OK: Did it actually open? Data: ' + JSON.stringify(res));
				}

				var openErr = function(res){
					console.log('FAILED: ' + JSON.stringify(res));
				};
				starprnt.openCashDrawer(openOK, openErr);
			}
		});
	}

	printReceipt() {
		starprnt.connect("BT:TSP100", function(err,res) {
			if (err) {
				console.log('FAILED: ' + JSON.stringify(err));
			} else if(res) {
				console.log('OK: ' + JSON.stringify(res));
				var printOK = function(res){
					console.log('OK: Did it actually open? Data: ' + JSON.stringify(res));
				}

				var printErr = function(res){
					console.log('FAILED: ' + JSON.stringify(res));
				};

				let content = "Star Clothing Boutique\n123 Star Road\nCity, State 12345\n";

				starprnt.printData(content, printOK, printErr);
			}
		});
	}
}

```

**Comment by infoxicator** [comment]
Hi  @esthonwood  I have added emulation and the portsettings to the check status function on iOS, use the plugin from my [fork](https://github.com/infoxicator/starprnt) and let me know if it works on the TSP100. you can see some examples from my [test app](https://github.com/infoxicator/StarprntDemo-Ionic1). I am working on updating all the functions to support both printing methods SMPort(pass port and emulation) and StarioExtManager (send commands to connected printer)

**Comment by esthonwood** [comment]
Hi @infoxicator, did you also update the StarPRNT SDK version to 5.5.0?

**Comment by infoxicator** [comment]
Hi @esthonwood I have updated it on my fork, but I am testing it at the moment I will commit the new version soon... Did you manage to connect to the TSP100?

**Comment by esthonwood** [comment]
Hi @infoxicator it still won't print on the TSP100. Please let me know when your fork is ready to use. Thanks.

**Comment by daniellizik** [comment]
Can reproduce, tried doing this in the js console
```
window.starprnt.printRawText(
  'BT:TSP100',
  'StarGraphic',
  { text: 'lfkajsldfjajkdljfkljklfこんにちは' },
  s => alert(JSON.stringify(s)),
  e => alert(JSON.stringify(e))
)
```
I get the success alert but nothing prints. Using `.print()` I can only get the `appendCutPaper` print command to elicit a response from the printer (it doesn't actually cut though), no other print commands seem to do anything.

xcode debugger:
```
2019-02-21 11:46:49.690424+0900 app[3420:3503307] accessoryd sessionResult = 1, useSocketInterace = 1, sessionID = 0x16
2019-02-21 11:46:51.623522+0900 app[3420:3503307] Removing EASession 9AFD3601-E528-45C3-BA79-9E9B8D13F06B from list of sessionUUIDs
```

**Comment by daniellizik** [comment]
@esthonwood I emailed star micronics sales support in Japan, and they said that TSP100iiiBI (starGraphics emulation) only supports printing raster images.
