### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by infoxicator** [auctifera-josed/starprnt#4]
Hi Jose, 

I am working on adding Android support to this plugin, I also want to standardize the functions so they could be used regardless of the receipt format, I can create a new PR if that's easy to collaborate?

thanks

Ruben

**Comment by auctifera-josed** [comment]
Yes, please do. Remember you can take a look at [StarIOPlugin](https://github.com/InteractiveObject/StarIOPlugin/tree/master/src/android), they have android support and could give you some ideas.

**Comment by joesalloum** [comment]
we need the android version as soon as possible including the black mark feature if possible, i want to use it for star L300 couldn't find any plugin for it

**Comment by joesalloum** [comment]
@infoxicator @auctifera-josed Any News concerning the android version ???

**Comment by infoxicator** [comment]
@auctifera-josed @joesalloum I have been working on my fork, basic android support is now available however I don't recommend using it yet because there might be breaking changes... I have added emulation type so all printer models should be available (android only for now) have a look at my app example for [ionic1](https://github.com/infoxicator/StarprntDemo-Ionic1). (Ionic2 native plugin coming soon)

**Comment by joesalloum** [comment]
@infoxicator thank you but i wanted the plugin for cordova not ionic project
